local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("viz's script library", "DarkTheme")
local mainTab = Window:NewTab("Main")
local mainSec = Window:NewSection("Main")
mainSec:NewKeybind("Toggle UI", "Toggle the Script Hub", Enum.KeyCode.F, function()
	Library:ToggleUI()
end)
local admTab = Window:NewTab("Admin Commands")
local adbSec = Tab:NewSection("Best Admin Scripts")
adbSec:NewLabel("HEADS UP! Any of the scripts here are not verified by viz, nor created by him. Please proceed with caution, and make sure to use an alt.")
adbSec:NewButton("Infinite Yield", "Execute Infinite Yield", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'))()
end)
--
adbSec:NewButton("Nameless Admin", "Execute NA", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/FilteringEnabled/NamelessAdmin/main/Source'))()
end)
--
adbSec:NewButton("QuirkyCmd", "Execute", function()
    loadstring(game:HttpGet("https://gist.github.com/someunknowndude/38cecea5be9d75cb743eac8b1eaf6758/raw"))()
end)
--loadstring(game:HttpGet(" https://rawscripts.net/raw/Universal-Script-Brick-Admin-BETA-12105",true))()
adbSec:NewButton("Brick Admin BETA", "Execute", function()
    loadstring(game:HttpGet("https://rawscripts.net/raw/Universal-Script-Brick-Admin-BETA-12105",true))()
end)
