local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("viz's script library", "DarkTheme")
local mainTab = Window:NewTab("Main")
local mainSec = Window:NewSection("Main")
mainSec:NewKeybind("Toggle UI", "Toggle the Script Hub", Enum.KeyCode.F, function()
	Library:ToggleUI()
end)
local admTab = Window:NewTab("Admin Commands")
local admSec = Tab:NewSection("Best Admin Scripts")
adbSec:NewButton("Infinite Yield", "Execute Infinite Yield", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'))()
end)
